# Generated by Django 5.0.6 on 2024-07-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_customuser_id_number_remove_customuser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deletion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
